INSERT INTO [TBL_district_code] VALUES(01,99,'Srinagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(01,21,'Jammu UA','UA')
INSERT INTO [TBL_district_code] VALUES(01,99,'Anantnag UA','UA')
INSERT INTO [TBL_district_code] VALUES(02,11,'Shimla UA','UA')
INSERT INTO [TBL_district_code] VALUES(03,7,'Ludhiana (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(03,15,'Amritsar UA','UA')
INSERT INTO [TBL_district_code] VALUES(03,3,'Jalandhar UA','UA')
INSERT INTO [TBL_district_code] VALUES(03,14,'Patiala UA','UA')
INSERT INTO [TBL_district_code] VALUES(03,12,'Bathinda (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(03,18,'S.A.S. Nagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(03,4,'Hoshiarpur (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(03,1,'Pathankot UA','UA')
INSERT INTO [TBL_district_code] VALUES(03,8,'Moga UA','UA')
INSERT INTO [TBL_district_code] VALUES(03,1,'Batala UA','UA')
INSERT INTO [TBL_district_code] VALUES(03,9,'Abohar (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(03,19,'Malerkotla (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(03,7,'Khanna (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(03,2,'Phagwara UA','UA')
INSERT INTO [TBL_district_code] VALUES(03,10,'Muktsar (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(03,20,'Barnala (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(03,9,'Firozpur (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(03,2,'Kapurthala (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(04,01,'Chandigarh UA','UA')
INSERT INTO [TBL_district_code] VALUES(05,05,'Dehradun UA','UA')
INSERT INTO [TBL_district_code] VALUES(05,13,'Hardwar UA','UA')
INSERT INTO [TBL_district_code] VALUES(05,13,'Roorkee UA','UA')
INSERT INTO [TBL_district_code] VALUES(05,11,'Haldwani-cum-Kathgodam UA','UA')
INSERT INTO [TBL_district_code] VALUES(05,12,'Rudrapur UA','UA')
INSERT INTO [TBL_district_code] VALUES(05,12,'Kashipur (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(05,05,'Rishikesh UA','UA')
INSERT INTO [TBL_district_code] VALUES(06,20,'Faridabad (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(06,18,'Gurgaon UA','UA')
INSERT INTO [TBL_district_code] VALUES(06,07,'Panipat UA','UA')
INSERT INTO [TBL_district_code] VALUES(06,03,'Yamunanagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(06,14,'Rohtak (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(06,12,'Hisar UA','UA')
INSERT INTO [TBL_district_code] VALUES(06,06,'Karnal UA','UA')
INSERT INTO [TBL_district_code] VALUES(06,08,'Sonipat UA','UA')
INSERT INTO [TBL_district_code] VALUES(06,01,'Panchkula (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(06,02,'Ambala UA','UA')
INSERT INTO [TBL_district_code] VALUES(06,13,'Bhiwani (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(06,02,'Ambala (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(06,11,'Sirsa (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(06,15,'Bahadurgarh (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(06,09,'Jind (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(06,04,'Thanesar (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(06,05,'Kaithal (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(06,17,'Rewari (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(06,21,'Palwal UA','UA')
INSERT INTO [TBL_district_code] VALUES(07,99,'Delhi UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,12,'Jaipur (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(08,15,'Jodhpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,29,'Kota (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(08,03,'Bikaner (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(08,21,'Ajmer UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,32,'Udaipur UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,24,'Bhilwara (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(08,06,'Alwar UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,07,'Bharatpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,01,'Ganganagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,13,'Sikar UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,20,'Pali (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(08,22,'Tonk (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(08,21,'Kishangarh (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(08,21,'Beawar UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,02,'Total Hanumangarh (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(08,08,'Dhaulpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,10,'Gangapur City UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,10,'Sawai Madhopur (M)','City')
INSERT INTO [TBL_district_code] VALUES(08,04,'Churu UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,05,'Jhunjhunun (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(08,30,'Baran (M)','City')
INSERT INTO [TBL_district_code] VALUES(08,28,'Chittaurgarh (M)','City')
INSERT INTO [TBL_district_code] VALUES(08,14,'Makrana UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,14,'Nagaur UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,09,'Hindaun (M)','City')
INSERT INTO [TBL_district_code] VALUES(08,06,'Bhiwadi (M)','City')
INSERT INTO [TBL_district_code] VALUES(08,23,'Bundi UA','UA')
INSERT INTO [TBL_district_code] VALUES(08,04,'Sujangarh (M)','City')
INSERT INTO [TBL_district_code] VALUES(08,27,'Banswara UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,33,'Kanpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,26,'Lucknow UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,09,'Ghaziabad UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,15,'Agra UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,66,'Varanasi UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,07,'Meerut UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,44,'Allahabad UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,19,'Bareilly UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,12,'Aligarh UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,04,'Moradabad (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(09,01,'Saharanpur (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(09,57,'Gorakhpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,10,'Noida (CT)','CT')
INSERT INTO [TBL_district_code] VALUES(09,16,'Firozabad (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,35,'Jhansi UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,02,'Muzaffarnagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,14,'Mathura UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,05,'Rampur UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,21,'Shahjahanpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,28,'Farrukhabad-cum-Fatehgarh UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,61,'Maunath Bhanjan (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,09,'Hapur (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,46,'Faizabad UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,30,'Etawah (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,68,'Mirzapur-cum-Vindhyachal UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,11,'Bulandshahr UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,04,'Sambhal (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,06,'Amroha (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,24,'Hardoi UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,41,'Fatehpur (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,27,'Rae Bareli (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,34,'Orai UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,23,'Sitapur UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,49,'Bahraich (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,09,'Modinagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,25,'Unnao (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,63,'Jaunpur (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,22,'Lakhimpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,13,'Hathras UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,39,'Banda UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,20,'Pilibhit UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,18,'Budaun (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,65,'Mughalsarai UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,45,'Barabanki UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,11,'Khurja UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,52,'Gonda UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,17,'Mainpuri UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,36,'Lalitpur (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,70,'Etah UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,59,'Deoria (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,64,'Ghazipur UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,48,'Sultanpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,60,'Azamgarh UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,03,'Bijnor UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,54,'Basti (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,04,'Chandausi (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,47,'Akbarpur (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,62,'Ballia UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,60,'Mubarakpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(09,10,'Greater Noida (CT)','CT')
INSERT INTO [TBL_district_code] VALUES(09,16,'Shikohabad (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,02,'Shamli (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,08,'Baraut (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(09,71,'Kasganj (NPP)','City')
INSERT INTO [TBL_district_code] VALUES(10,28,'Patna UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,34,'Gaya UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,22,'Bhagalpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,14,'Muzaffarpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,09,'Purnia UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,13,'Darbhanga UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,27,'Biharsharif (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(10,29,'Arrah (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(10,20,'Begusarai (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(10,10,'Katihar UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,24,'Munger (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(10,17,'Chapra UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,01,'Bettiah UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,12,'Saharsa (NP)','City')
INSERT INTO [TBL_district_code] VALUES(10,32,'Sasaram (NP)','City')
INSERT INTO [TBL_district_code] VALUES(10,18,'Hajipur (NP)','City')
INSERT INTO [TBL_district_code] VALUES(10,32,'Dehri (NP)','City')
INSERT INTO [TBL_district_code] VALUES(10,16,'Siwan (NP)','City')
INSERT INTO [TBL_district_code] VALUES(10,02,'Motihari (NP)','City')
INSERT INTO [TBL_district_code] VALUES(10,35,'Nawada UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,01,'Bagaha (NP)','City')
INSERT INTO [TBL_district_code] VALUES(10,30,'Buxar UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,08,'Kishanganj (NP)','City')
INSERT INTO [TBL_district_code] VALUES(10,04,'Sitamarhi UA','UA')
INSERT INTO [TBL_district_code] VALUES(10,24,'Jamalpur (NP)','City')
INSERT INTO [TBL_district_code] VALUES(10,37,'Jehanabad (NP)','City')
INSERT INTO [TBL_district_code] VALUES(10,33,'Aurangabad (NP)','City')
INSERT INTO [TBL_district_code] VALUES(13,05,'Dimapur (MC)','City')
INSERT INTO [TBL_district_code] VALUES(14,99,'Imphal UA','UA')
INSERT INTO [TBL_district_code] VALUES(15,03,'Aizawl (NT)','City')
INSERT INTO [TBL_district_code] VALUES(16,01,'Agartala (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(17,06,'Shillong UA','UA')
INSERT INTO [TBL_district_code] VALUES(18,23,'Guwahati UA','UA')
INSERT INTO [TBL_district_code] VALUES(18,17,'Silchar UA','UA')
INSERT INTO [TBL_district_code] VALUES(18,11,'Dibrugarh UA','UA')
INSERT INTO [TBL_district_code] VALUES(18,13,'Jorhat UA','UA')
INSERT INTO [TBL_district_code] VALUES(18,06,'Nagaon UA','UA')
INSERT INTO [TBL_district_code] VALUES(18,10,'Tinsukia UA','UA')
INSERT INTO [TBL_district_code] VALUES(18,07,'Tezpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,99,'Kolkata UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,09,'Asansol UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,99,'Siliguri UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,09,'Durgapur UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,09,'Barddhaman UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,06,'English Bazar UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,07,'Baharampur UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,11,'Habra UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,18,'Kharagpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,10,'Santipur UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,12,'Dankuni UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,07,'Dhulian UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,10,'Ranaghat UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,19,'Haldia (M)','City')
INSERT INTO [TBL_district_code] VALUES(19,04,'Raiganj UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,10,'Krishnanagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,10,'Nabadwip UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,18,'Medinipur (M)','City')
INSERT INTO [TBL_district_code] VALUES(19,02,'Jalpaiguri UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,05,'Balurghat UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,11,'Basirhat UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,13,'Bankura (M)','City')
INSERT INTO [TBL_district_code] VALUES(19,10,'Chakdaha UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,01,'Darjiling UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,02,'Alipurduar UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,14,'Puruliya UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,07,'Jangipur UA','UA')
INSERT INTO [TBL_district_code] VALUES(19,11,'Bongaon (M)','City')
INSERT INTO [TBL_district_code] VALUES(19,03,'Koch Bihar UA','UA')
INSERT INTO [TBL_district_code] VALUES(20,99,'Jamshedpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(20,09,'Dhanbad UA','UA')
INSERT INTO [TBL_district_code] VALUES(20,19,'Ranchi UA','UA')
INSERT INTO [TBL_district_code] VALUES(20,10,'Bokaro Steel City UA','UA')
INSERT INTO [TBL_district_code] VALUES(20,05,'Deoghar (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(20,10,'Phusro UA','UA')
INSERT INTO [TBL_district_code] VALUES(20,15,'Hazaribag UA','UA')
INSERT INTO [TBL_district_code] VALUES(20,04,'Giridih UA','UA')
INSERT INTO [TBL_district_code] VALUES(20,16,'Ramgarh UA','UA')
INSERT INTO [TBL_district_code] VALUES(20,13,'Medini Nagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(20,09,'Chirkunda UA','UA')
INSERT INTO [TBL_district_code] VALUES(21,17,'Bhubaneswar UA','UA')
INSERT INTO [TBL_district_code] VALUES(21,12,'Cuttack UA','UA')
INSERT INTO [TBL_district_code] VALUES(21,05,'Raurkela UA','UA')
INSERT INTO [TBL_district_code] VALUES(21,19,'Brahmapur Town (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(21,03,'Sambalpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(21,18,'Puri Town (M)','City')
INSERT INTO [TBL_district_code] VALUES(21,08,'Baleshwar UA','UA')
INSERT INTO [TBL_district_code] VALUES(21,09,'Bhadrak UA','UA')
INSERT INTO [TBL_district_code] VALUES(21,07,'Baripada UA','UA')
INSERT INTO [TBL_district_code] VALUES(22,11,'Raipur UA','UA')
INSERT INTO [TBL_district_code] VALUES(22,10,'Durg-Bhilainagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(22,07,'Bilaspur UA','UA')
INSERT INTO [TBL_district_code] VALUES(22,05,'Korba UA','UA')
INSERT INTO [TBL_district_code] VALUES(22,09,'Rajnandgaon (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(22,04,'Raigarh UA','UA')
INSERT INTO [TBL_district_code] VALUES(22,15,'Jagdalpur (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(22,02,'Ambikapur UA','UA')
INSERT INTO [TBL_district_code] VALUES(22,13,'Dhamtari UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,22,'Indore UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,27,'Bhopal UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,34,'Jabalpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,04,'Gwalior UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,18,'Ujjain (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(23,10,'Sagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,20,'Dewas (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(23,12,'Satna UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,17,'Ratlam UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,13,'Rewa (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(23,33,'Murwara (Katni) (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(23,46,'Singrauli (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(23,50,'Burhanpur (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(23,49,'Khandwa (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(23,02,'Morena (M)','City')
INSERT INTO [TBL_district_code] VALUES(23,03,'Bhind (M)','City')
INSERT INTO [TBL_district_code] VALUES(23,38,'Chhindwara UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,41,'Guna (M)','City')
INSERT INTO [TBL_district_code] VALUES(23,06,'Shivpuri (M)','City')
INSERT INTO [TBL_district_code] VALUES(23,26,'Vidisha (M)','City')
INSERT INTO [TBL_district_code] VALUES(23,08,'Chhattarpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,11,'Damoh UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,16,'Mandsaur (M)','City')
INSERT INTO [TBL_district_code] VALUES(23,23,'Khargone UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,15,'Neemuch UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,21,'Pithampur (M)','City')
INSERT INTO [TBL_district_code] VALUES(23,32,'Hoshangabad (M)','City')
INSERT INTO [TBL_district_code] VALUES(23,32,'Itarsi UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,28,'Sehore UA','UA')
INSERT INTO [TBL_district_code] VALUES(23,30,'Betul (M)','City')
INSERT INTO [TBL_district_code] VALUES(23,39,'Seoni (M)','City')
INSERT INTO [TBL_district_code] VALUES(23,05,'Datia (M)','City')
INSERT INTO [TBL_district_code] VALUES(23,18,'Nagda (M)','City')
INSERT INTO [TBL_district_code] VALUES(24,99,'Ahmadabad UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,25,'Surat UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,19,'Vadodara UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,09,'Rajkot UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,14,'Bhavnagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,10,'Jamnagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,12,'Junagadh (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(24,15,'Anand UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,23,'Navsari UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,08,'Wadhwan UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,01,'Gandhidham (M)','City')
INSERT INTO [TBL_district_code] VALUES(24,09,'Morvi UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,16,'Nadiad UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,21,'Bharuch UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,11,'Porbandar UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,04,'Mahesana UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,01,'Bhuj UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,12,'Veraval UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,24,'Valsad UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,24,'Vapi (M)','City')
INSERT INTO [TBL_district_code] VALUES(24,17,'Godhra UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,21,'Anklesvar UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,02,'Palanpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,03,'Patan UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,14,'Botad (M)','City')
INSERT INTO [TBL_district_code] VALUES(24,18,'Dohad UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,09,'Jetpur Navagadh (M)','City')
INSERT INTO [TBL_district_code] VALUES(24,13,'Amreli UA','UA')
INSERT INTO [TBL_district_code] VALUES(24,09,'Gondal (M)','City')
INSERT INTO [TBL_district_code] VALUES(24,02,'Deesa (M)','City')
INSERT INTO [TBL_district_code] VALUES(27,99,'Greater Mumbai UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,25,'Pune UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,09,'Nagpur UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,20,'Nashik UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,21,'Vasai Virar City (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(27,19,'Aurangabad UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,30,'Solapur (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(27,21,'Bhiwandi UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,07,'Amravati (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(27,20,'Malegaon UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,34,'Kolhapur UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,15,'Nanded Waghala (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(27,35,'Sangali UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,03,'Jalgaon (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(27,05,'Akola (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(27,28,'Latur (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,26,'Ahmadnagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,02,'Dhule (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(27,34,'Ichalkaranji UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,13,'Chandrapur (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,17,'Parbhani (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,18,'Jalna (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,03,'Bhusawal UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,24,'Navi Mumbai Panvel Raigad (CT)','CT')
INSERT INTO [TBL_district_code] VALUES(27,24,'Panvel (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,31,'Satara UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,27,'Bid (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,14,'Yavatmal UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,09,'Kamptee UA','UA')
INSERT INTO [TBL_district_code] VALUES(27,11,'Gondiya (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,30,'Barshi (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,07,'Achalpur (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,29,'Osmanabad (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,01,'Nandurbar (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,08,'Wardha (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,28,'Udgir (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(27,08,'Hinganghat (M Cl)','City')
INSERT INTO [TBL_district_code] VALUES(28,99,'Hyderabad UA ','UA')
INSERT INTO [TBL_district_code] VALUES(28,13,'GVMC (MC)','City')
INSERT INTO [TBL_district_code] VALUES(28,99,'Vijayawada UA ','UA')
INSERT INTO [TBL_district_code] VALUES(28,09,'Warangal UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,17,'Guntur UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,19,'Nellore UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,14,'Rajahmundry UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,21,'Kurnool UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,23,'Tirupati UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,14,'Kakinada UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,20,'Kadapa UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,22,'Anantapur UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,02,'Nizamabad (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(28,03,'Karimnagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,10,'Khammam UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,03,'Ramagundam UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,15,'Eluru UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,12,'Vizianagaram UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,20,'Proddatur UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,21,'Nandyal UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,07,'Mahbubnagar UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,18,'Ongole UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,21,'Adoni UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,23,'Madanapalle UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,23,'Chittoor UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,16,'Machilipatnam (M)','City')
INSERT INTO [TBL_district_code] VALUES(28,17,'Tenali (M)','City')
INSERT INTO [TBL_district_code] VALUES(28,01,'Mancherial UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,18,'Chirala UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,08,'Nalgonda UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,22,'Hindupur (M)','City')
INSERT INTO [TBL_district_code] VALUES(28,15,'Bhimavaram UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,11,'Srikakulam UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,01,'Adilabad UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,22,'Guntakal (M)','City')
INSERT INTO [TBL_district_code] VALUES(28,22,'Dharmavaram (M)','City')
INSERT INTO [TBL_district_code] VALUES(28,10,'Kothagudem UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,16,'Gudivada (M)','City')
INSERT INTO [TBL_district_code] VALUES(28,17,'Narasaraopet UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,04,'Siddipet UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,22,'Tadpatri (M)','City')
INSERT INTO [TBL_district_code] VALUES(28,08,'Suryapet UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,08,'Miryalaguda UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,03,'Jagtial UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,15,'Tadepalligudem UA','UA')
INSERT INTO [TBL_district_code] VALUES(28,17,'Chilakaluripet (M)','City')
INSERT INTO [TBL_district_code] VALUES(29,18,'BANGALORE UA','UA')
INSERT INTO [TBL_district_code] VALUES(29,23,'Mysore UA','UA')
INSERT INTO [TBL_district_code] VALUES(29,08,'Hubli-Dharwad *(M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(29,21,'Mangalore UA','UA')
INSERT INTO [TBL_district_code] VALUES(29,01,'Belgaum UA','UA')
INSERT INTO [TBL_district_code] VALUES(29,25,'Gulbarga UA','UA')
INSERT INTO [TBL_district_code] VALUES(29,13,'Davanagere (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(29,11,'Bellary (M Corp.)','City')
INSERT INTO [TBL_district_code] VALUES(29,03,'Bijapur (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(29,14,'Shimoga (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(29,17,'Tumkur (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(29,05,'Raichur (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(29,04,'Bidar UA','UA')
INSERT INTO [TBL_district_code] VALUES(29,11,'Hospet (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(29,20,'Hassan UA','UA')
INSERT INTO [TBL_district_code] VALUES(29,07,'Gadag-Betigeri (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(29,27,'Robertson Pet UA','UA')
INSERT INTO [TBL_district_code] VALUES(29,15,'Udupi UA','UA')
INSERT INTO [TBL_district_code] VALUES(29,14,'Bhadravati (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(29,12,'Chitradurga UA','UA')
INSERT INTO [TBL_district_code] VALUES(29,27,'Kolar (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(29,19,'Mandya (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(29,16,'Chikmagalur (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(29,06,'Gangawati UA','UA')
INSERT INTO [TBL_district_code] VALUES(29,02,'Bagalkot (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(29,10,'Ranibennur (CMC)','City')
INSERT INTO [TBL_district_code] VALUES(30,01,'Panaji UA','UA')
INSERT INTO [TBL_district_code] VALUES(30,02,'Margao UA','UA')
INSERT INTO [TBL_district_code] VALUES(30,02,'Mormugao UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,08,'Kochi UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,04,'Kozhikode UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,07,'Thrissur UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,05,'Malappuram UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,14,'Thiruvananthapuram UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,02,'Kannur UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,13,'Kollam UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,11,'Cherthala UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,11,'Kayamkulam UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,10,'Kottayam UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,06,'Palakkad UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,11,'Alappuzha UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,06,'Ottappalam UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,01,'Kanhangad UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,01,'Kasaragod UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,10,'Changanassery UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,07,'Chalakudy UA','UA')
INSERT INTO [TBL_district_code] VALUES(32,08,'Kothamangalam UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,99,'Chennai UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,31,'Coimbatore UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,22,'Madurai UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,13,'Tiruchirappalli UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,32,'Tiruppur UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,07,'Salem UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,09,'Erode UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,27,'Tirunelveli UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,04,'Vellore UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,26,'Thoothukkudi UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,11,'Dindigul UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,19,'Thanjavur UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,04,'Ranipet UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,24,'Sivakasi UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,12,'Karur UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,10,'Udhagamandalam UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,30,'Hosur UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,28,'Nagercoil (M)','City')
INSERT INTO [TBL_district_code] VALUES(33,03,'Kancheepuram UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,08,'Kumarapalayam UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,21,'Karaikkudi UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,16,'Neyveli UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,16,'Cuddalore (M)','City')
INSERT INTO [TBL_district_code] VALUES(33,19,'Kumbakonam UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,05,'Tiruvannamalai (M)','City')
INSERT INTO [TBL_district_code] VALUES(33,31,'Pollachi UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,24,'Rajapalayam (M)','City')
INSERT INTO [TBL_district_code] VALUES(33,04,'Gudiyatham UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,20,'Pudukkottai (M)','City')
INSERT INTO [TBL_district_code] VALUES(33,04,'Vaniyambadi UA','UA')
INSERT INTO [TBL_district_code] VALUES(33,04,'Ambur (M)','City')
INSERT INTO [TBL_district_code] VALUES(33,17,'Nagapattinam (M)','City')
INSERT INTO [TBL_district_code] VALUES(34,02,'Puducherry UA','UA')
INSERT INTO [TBL_district_code] VALUES(35,03,'Port Blair (MC)','City')
